const getters = {
  // sidebar: state => state.app.sidebar,
  // device: state => state.app.device,
  userId: state => state.user.userId,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  // roles: state => state.user.roles,
  // perms: state => state.user.perms,
  // addRoutes: state => state.permission.addRoutes,
  // routes: state => state.permission.routes,
  // editableTabs: state => state.tag.editableTabs,
  // collapse: state => state.tag.collapse,
  productTitle: state => state.productDetail.productTitle,
  productSkusTitle: state => state.productDetail.productSkusTitle,
  productSKusIsLike: state => state.productDetail.productSKusIsLike,
  productSkusId: state => state.productDetail.productSkusId,
  productSkusInfo: state => state.productDetail.productSkusInfo,
  productSkusNumber: state => state.productDetail.productSkusNumber,
  productSkusStock: state => state.productDetail.productSkusStock,
  productSkusAvatar: state => state.productDetail.productSkusAvatar,
  productSkusSearchList: state => state.productDetail.productSkusSearchList,
  isSearch: state => state.productDetail.isSearch
}
export default getters
